const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {Library,same}=require('../course-library.js');
const copy=v=>JSON.parse(JSON.stringify(v));
const card=(id,name)=>({id,name,country:'Vietnam',region:'Da Nang',teeScorecards:{middle:{par:Array(18).fill(4),index:Array.from({length:18},(_,i)=>i+1),metres:Array(18).fill(274),yards:Array(18).fill(300),distanceUnit:'yards',distanceInputUnit:'yards'}}});
const records=new Map(),history=new Map(),countries=[];let allowed=true,offline=false,saveGate=null;
const api={async loadCourseLibrary(){if(!allowed)throw Object.assign(new Error('No access'),{code:'42501'});return {courses:[...records.values()].map(copy),countries:[...countries]};},async saveMasterCourse(id,data,revision){if(saveGate)await saveGate;const old=records.get(id);if(old ? old.revision!==revision : revision!==null)throw Object.assign(new Error('Stale'),{code:'40001'});const row={id,data:copy(data),revision:old?old.revision+1:1};records.set(id,row);history.set(id,[...(history.get(id)||[]),copy(row)]);return copy(row);},async loadMasterCourse(id){return copy(records.get(id));},async saveMasterCountry(name){if(!countries.some(v=>v.toLowerCase()===name.toLowerCase()))countries.push(name);}};
function device(initial){let store={courses:copy(initial),courseCountries:['Australia','Vietnam']},written;const library=new Library({store:()=>store,api,persist:()=>{written=copy(store);return true;},changed(){},online:()=>!offline});return {library,get store(){return store},restart(){store=copy(written);return new Library({store:()=>store,api,persist:()=>{written=copy(store);return true},online:()=>!offline});}};}
(async()=>{
 const pc=device([card('c1','Course One'),card('c2','Course Two')]);await pc.library.sync();assert.equal(records.size,2);assert.equal(pc.library.status('c1'),'Cloud revision 1');assert(countries.includes('Vietnam'));
 const tablet=device([]);await tablet.library.sync();assert.equal(tablet.store.courses.length,2);assert.equal(tablet.store.courses[0].teeScorecards.middle.yards[0],300);
 pc.store.courses[0].teeScorecards.middle.index[0]='1/19';pc.library.queue(pc.store.courses[0]);await pc.library.sync();await tablet.library.sync();assert.equal(tablet.store.courses[0].teeScorecards.middle.index[0],'1/19');assert.equal(history.get('c1').length,2);
 offline=true;tablet.store.courses[0].region='Hoi An';tablet.library.queue(tablet.store.courses[0]);await tablet.library.sync();assert.equal(tablet.library.status('c1'),'Cloud save pending');const resumed=tablet.restart();assert.equal(resumed.state().pending.c1.region,'Hoi An');offline=false;
 pc.store.courses[1].name='Course Two Updated';pc.library.queue(pc.store.courses[1]);await pc.library.sync();await resumed.sync();assert.equal(records.get('c1').data.region,'Hoi An');assert.equal(tablet.store.courses[1].name,'Course Two Updated');
 // PC keeps an older c1 revision while tablet changes it again.
 tablet.store.courses[0].name='Tablet New Name';resumed.queue(tablet.store.courses[0]);await resumed.sync();pc.store.courses[0].name='PC Alternative';pc.library.queue(pc.store.courses[0]);await pc.library.sync();assert.equal(pc.library.status('c1'),'Review two copies');assert.equal(pc.store.courses[0].name,'PC Alternative');assert.equal(records.get('c1').data.name,'Tablet New Name');
 pc.library.resolve('c1','cloud');assert.equal(pc.store.courses[0].name,'Tablet New Name');assert.equal(pc.library.state().retainedLocal[0].data.name,'PC Alternative');await pc.library.sync();
 // Initial connection never overwrites either copy merely because IDs match.
 const oldDevice=device([card('c1','Old Device Name')]);await oldDevice.library.sync();assert.equal(oldDevice.library.status('c1'),'Review two copies');oldDevice.library.resolve('c1','local');await oldDevice.library.sync();assert.equal(records.get('c1').data.name,'Old Device Name');assert.equal(history.get('c1').at(-2).data.name,'Tablet New Name');
 // A save made while an earlier save awaits acknowledgement stays queued.
 await pc.library.sync();let release;saveGate=new Promise(r=>release=r);pc.store.courses[1].name='First Save';pc.library.queue(pc.store.courses[1]);const flight=pc.library.sync();await new Promise(r=>setImmediate(r));pc.store.courses[1].name='Second Save';pc.library.queue(pc.store.courses[1]);release();saveGate=null;await flight;await pc.library.sync();assert.equal(records.get('c2').data.name,'Second Save');assert.equal(pc.library.status('c2'),'Cloud revision 4');
 // A stale/superseded tab must not start a remote write.
 let writes=0;const blocked=new Library({store:()=>({courses:[card('blocked','Blocked')]}),api:{loadCourseLibrary:async()=>{writes++;return {courses:[],countries:[]}}},persist:()=>false,online:()=>true});await blocked.sync();assert.equal(writes,0);assert.match(blocked.message,/storage/);
 allowed=false;await pc.library.sync();assert.equal(pc.library.allowed,false);assert.match(pc.library.message,/Owner Sign-In/);allowed=true;
 assert(same({activeScorecardTee:'back',name:'A',x:{b:1,a:2}},{activeScorecardTee:'middle',x:{a:2,b:1},name:'A'}));
 // Current published cards use their snapshot; Course Details uses the master.
 const app=fs.readFileSync('app.js','utf8');const getter=app.match(/  const course = ([^\n]+),\n/)[1];const ctx={store:{courses:[{id:'c1',name:'New Master'}],event:{locked:true},cloud:{eventId:'event',courseCards:[{id:'c1',name:'Published Card'}]}}};vm.createContext(ctx);vm.runInContext('globalThis.course='+getter+';',ctx);assert.equal(ctx.course('c1').name,'Published Card');assert.equal(ctx.course('c1',true).name,'New Master');ctx.store.event.locked=false;assert.equal(ctx.course('c1').name,'New Master');
 // Legacy repair/consolidation must never rewrite the cloud master.
 ctx.store={courses:[{id:'oat',name:'Oatlands GC'}],courseLibrary:{bases:{oat:{revision:2}}}};
 for(const name of ['repairIncompleteOatlandsCard','enforceAuthoritativeOatlandsCard','consolidateCourseCards']){const start=app.indexOf('  function '+name+'('),end=app.indexOf('\n  }',start);vm.runInContext(app.slice(start,end+4),ctx);}
 assert.equal(ctx.repairIncompleteOatlandsCard(),false);assert.equal(ctx.enforceAuthoritativeOatlandsCard(),false);assert.equal(ctx.consolidateCourseCards(),undefined);
 console.log('Passed: two-device upload/download, full tee/yardage JSON, revisions/history, offline restart, independent edits, stale conflicts, initial-copy review, retained local alternatives, explicit resolution, in-flight newer edits, writer lease, denied access and published-card isolation.');
})().catch(e=>{console.error(e);process.exitCode=1});
