import {createGroupApi,validateAccountConfig} from './group-api.mjs';
import {acceptedDetails,copyTeeCard} from './course-model.mjs';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
let client,api,courses=[],current=null,busy=false,dirty=false,reviewGroup=null,fullCatalogue=false;
const fields=[['name','Course name'],['region','Region'],['address','Address'],['website','Website'],['clubPhone','Club phone'],['clubEmail','Club email'],['proName','Professional’s name'],['proPhone','Pro shop phone'],['proEmail','Pro shop email'],['mapLink','Map link'],['notes','Notes']];
function holeInputs(panel,field){return [...panel.querySelectorAll(`[data-card="${field}"]`)].sort((a,b)=>Number(a.dataset.hole)-Number(b.dataset.hole));}
function message(text,error=false){$('courseMessage').textContent=text;$('courseMessage').classList.toggle('error',error);}
function feedback(text,error=false){$('saveFeedback').textContent=text;$('saveFeedback').classList.toggle('error',error);}
function input(parent,key,label,value,type='text'){
 const l=document.createElement('label');l.textContent=label;const n=document.createElement(type==='textarea'?'textarea':'input');n.id=key;if(type!=='textarea')n.type=type;n.value=value??'';n.maxLength=type==='textarea'?2000:300;l.append(n);parent.append(l);return n;
}
function render(course){current=structuredClone(course);dirty=false;$('courseSelect').value=course.id;$('courseHeading').textContent=course.name;$('acceptedStatus').textContent=course.details.acceptedAt?`Last accepted: ${new Date(course.details.acceptedAt).toLocaleString()}`:'Imported details — awaiting owner acceptance.';$('courseFields').replaceChildren();$('teeEditors').replaceChildren();feedback('');
 for(const [key,label] of fields)input($('courseFields'),'field-'+key,label,key==='name'?course.name:course.details[key],key==='notes'?'textarea':'text');$('field-name').required=true;
 const keys=[...new Set(['back','middle','front',...Object.keys(course.details.teeDetails||{}),...Object.keys(course.details.teeScorecards||{})])];
 for(const key of keys){const info=course.details.teeDetails?.[key]||{},card=course.details.teeScorecards?.[key]||{};
  const panel=document.createElement('details');panel.className='tee-editor';panel.dataset.tee=key;panel.open=!!course.details.teeScorecards?.[key];const summary=document.createElement('summary');summary.textContent=`${info.name||key} tee`;panel.append(summary);
  const label=document.createElement('label');label.className='check';const included=document.createElement('input');included.type='checkbox';included.className='include-tee';included.checked=!!course.details.teeScorecards?.[key];label.append(included,document.createTextNode('Include this accepted tee scorecard'));panel.append(label);
  const copyRow=document.createElement('div');copyRow.className='tee-copy-row';const copyLabel=document.createElement('label');copyLabel.textContent='Copy from tee';const copySelect=document.createElement('select');copySelect.setAttribute('aria-label',`Copy scorecard into ${info.name||key} from`);const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Choose tee';copySelect.append(placeholder);
  for(const sourceKey of keys.filter(k=>k!==key)){const option=document.createElement('option');option.value=sourceKey;const sourceInfo=course.details.teeDetails?.[sourceKey]||{};option.textContent=`${sourceInfo.name||sourceKey}${sourceInfo.colour?' · '+sourceInfo.colour:''}`;copySelect.append(option);}copyLabel.append(copySelect);copyRow.append(copyLabel);const copyButton=document.createElement('button');copyButton.type='button';copyButton.className='secondary';copyButton.textContent=`Copy into ${info.name||key}`;copyRow.append(copyButton);const modeLabel=document.createElement('label');modeLabel.textContent='Copy';const mode=document.createElement('select');for(const [value,text] of [['whole','Whole Card'],['column','Column']]){const option=document.createElement('option');option.value=value;option.textContent=text;mode.append(option);}modeLabel.append(mode);const columnLabel=document.createElement('label');columnLabel.textContent='Choose column';columnLabel.hidden=true;const column=document.createElement('select');for(const [value,text] of [['par','Par'],['index','Index'],['metres','Metres']]){const option=document.createElement('option');option.value=value;option.textContent=text;column.append(option);}columnLabel.append(column);copyRow.insertBefore(modeLabel,copyButton);copyRow.insertBefore(columnLabel,copyButton);mode.onchange=()=>columnLabel.hidden=mode.value!=='column';panel.append(copyRow);const help=document.createElement('p');help.className='copy-help';help.textContent='Copy the whole card or just Par, Index or Metres. Other columns and tee ratings stay unchanged when copying one column.';panel.append(help);const copyStatus=document.createElement('p');copyStatus.className='copy-status';copyStatus.setAttribute('role','status');panel.append(copyStatus);
  copyButton.onclick=()=>{if(busy)return;try{const sourcePanel=[...$('teeEditors').children].find(p=>p.dataset.tee===copySelect.value);if(!sourcePanel)throw Error('Choose the tee scorecard you want to copy from.');const source={};for(const field of ['par','index','metres'])source[field]=holeInputs(sourcePanel,field).map(n=>n.value);const selection=mode.value==='column'?column.value:'whole';const card=copyTeeCard(source,key,selection);const sourceName=sourcePanel.querySelector('[data-info="name"]').value||copySelect.value;const destinationName=panel.querySelector('[data-info="name"]').value||key;if(!window.confirm(`Copy ${selection==='whole'?'all 18 pars, indexes and metres':'only the '+selection+' column'} from ${sourceName} into ${destinationName}? This replaces those numbers currently entered for ${destinationName}.`))return;for(const field of selection==='whole'?['par','index','metres']:[selection])holeInputs(panel,field).forEach((n,i)=>n.value=card[field][i]);included.checked=true;panel.dispatchEvent(new Event('input',{bubbles:true}));copyStatus.textContent=`Copied from ${sourceName}. Check this tee’s distances and ratings, then save the accepted course details.`;copyStatus.classList.remove('error');}catch(e){copyStatus.textContent=e.message;copyStatus.classList.add('error');}};
  const edit=document.createElement('fieldset');const grid=document.createElement('div');grid.className='tee-grid';edit.append(grid);
  for(const [field,title] of [['name','Tee name'],['colour','Tee colour'],['slope','Slope rating'],['scratch','Scratch rating']]){const n=input(grid,`${key}-${field}`,title,info[field],['slope','scratch'].includes(field)?'number':'text');n.dataset.info=field;if(field==='scratch')n.step='0.1';}
  const totalPar=input(grid,`${key}-totalPar`,'Total par',0);totalPar.readOnly=true;totalPar.className='calculated-total';const totalMetres=input(grid,`${key}-totalMetres`,'Total metres',0);totalMetres.readOnly=true;totalMetres.className='calculated-total';
  const wrap=document.createElement('div');wrap.className='table-scroll';const table=document.createElement('table');table.className='scorecard';const head=document.createElement('tr');for(const text of ['Hole','Par','Index','Metres','Hole','Par','Index','Metres']){const th=document.createElement('th');th.textContent=text;th.scope='col';head.append(th);}const thead=document.createElement('thead');thead.append(head);table.append(thead);const tbody=document.createElement('tbody');const entryOrder=Array(54);
  for(let rowIndex=0;rowIndex<9;rowIndex++){const row=document.createElement('tr');for(const i of [rowIndex,rowIndex+9]){const h=document.createElement('th');h.scope='row';h.className='hole-number';h.textContent=i+1;row.append(h);for(const [fieldIndex,field] of ['par','index','metres'].entries()){const td=document.createElement('td');const n=document.createElement('input');n.type=field==='index'?'text':'number';n.inputMode=field==='index'?'text':'numeric';n.setAttribute('aria-label',`${info.name||key} hole ${i+1} ${field}`);n.dataset.card=field;n.dataset.hole=i;n.value=card[field]?.[i]??'';entryOrder[i*3+fieldIndex]=n;td.append(n);row.append(td);}}tbody.append(row);}table.append(tbody);
  entryOrder.forEach((n,i)=>n.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();const next=entryOrder[i+1];if(next){next.focus();next.select();}}}));wrap.append(table);edit.append(wrap);panel.append(edit);$('teeEditors').append(panel);
  const update=()=>{edit.disabled=!included.checked;const sum=field=>holeInputs(panel,field).reduce((a,n)=>a+(Number(n.value)||0),0);totalPar.value=sum('par');totalMetres.value=sum('metres');};included.onchange=update;panel.addEventListener('input',update);update();
 }
 $('courseEditor').hidden=false;
 let localButton=$('loadDeviceCourse');if(!localButton){localButton=document.createElement('button');localButton.id='loadDeviceCourse';localButton.type='button';localButton.className='secondary';$('saveFeedback').before(localButton);}
 let localCourse;try{const local=JSON.parse(localStorage.getItem('golfEventScorer13')||'null');localCourse=local?.courses?.find(c=>String(c.name).trim().toLowerCase()===String(course.name).trim().toLowerCase());}catch{}
 localButton.hidden=!localCourse;localButton.textContent='Review this device’s saved course details';localButton.onclick=()=>{if(!window.confirm('Load this device’s saved details into the form for review? The accepted online course will stay unchanged until you press Save as Accepted Course Details.'))return;const original=current;render({...original,details:{...original.details,...structuredClone(localCourse)}});current=original;dirty=true;feedback('Device details loaded for review only. Check each tee, then Save as Accepted Course Details to share them across devices.');localButton.hidden=true;};
}
async function load(preferred=current?.id){let rows=await api.courses();if(reviewGroup&&!fullCatalogue)rows=rows.filter(c=>reviewGroup.requested_course_ids.includes(c.id));courses=rows;$('catalogueScope').textContent=reviewGroup&&!fullCatalogue?reviewGroup.name+' · Selected courses':'Full course catalogue';$('showFullCatalogue').hidden=!reviewGroup||fullCatalogue;$('courseSelect').replaceChildren();for(const c of rows){const option=document.createElement('option');option.value=c.id;option.textContent=c.name;$('courseSelect').append(option);}const c=rows.find(c=>c.id===preferred)||rows[0];if(c){$('courseEditor').hidden=false;render(c);message('Edit the course, then save its accepted details.');}else{current=null;$('courseEditor').hidden=true;message('No selected courses are recorded for this customer.');}}
function mayDiscard(){return !dirty||window.confirm('Discard your unsaved course changes?');}
async function action(fn){if(busy)return;busy=true;for(const id of ['saveAccepted','reloadCourse','courseSelect'])$(id).disabled=true;try{await fn();}catch(e){message(e.message||'Unable to save course details.',true);feedback(e.message||'Unable to save. Your changes are still on this page.',true);$('saveFeedback').scrollIntoView({block:'center'});}finally{busy=false;for(const id of ['saveAccepted','reloadCourse','courseSelect'])$(id).disabled=false;}}
async function initialise(){const cfg=validateAccountConfig(window.GES_ACCOUNT_CONFIG);client=window.supabase.createClient(cfg.url,cfg.key,{auth:{storageKey:'golfEventScorerGroupAuth',persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});api=createGroupApi(client);const {data,error}=await client.auth.getUser();if(error||!data.user||!(await api.isOwner())){message('Sign in with your owner email on Groups & Organiser Accounts to edit courses.',true);return;}
 const group=params.get('group');if(group){reviewGroup=(await api.groups()).find(g=>g.id===group);if(!reviewGroup)throw new Error('Customer group is not available. Return to customer review.');}$('showFullCatalogue').onclick=()=>{if(mayDiscard()){fullCatalogue=true;action(()=>load());}};const back='groups.html'+(group?'?group='+encodeURIComponent(group):'')+'#review';$('returnReview').href=back;$('returnAfterSave').href=back;$('catalogue').hidden=false;await load(params.get('course'));
 $('courseSelect').onchange=()=>{const id=$('courseSelect').value;if(!mayDiscard()){$('courseSelect').value=current.id;return;}render(courses.find(c=>c.id===id));};$('reloadCourse').onclick=()=>{if(mayDiscard())action(()=>load());};$('saveCourse').oninput=()=>{dirty=true;feedback('Unsaved changes.');};
 $('saveCourse').onsubmit=e=>{e.preventDefault();action(async()=>{feedback('Saving accepted details…');const values={};for(const [key] of fields)if(key!=='name')values[key]=$('field-'+key).value.trim();const tees={};for(const panel of $('teeEditors').children){const key=panel.dataset.tee;const info={};panel.querySelectorAll('[data-info]').forEach(n=>info[n.dataset.info]=n.value.trim());const card={};for(const field of ['par','index','metres'])card[field]=holeInputs(panel,field).map(n=>n.value);tees[key]={included:panel.querySelector('.include-tee').checked,info,card};}
 const name=$('field-name').value.trim(),details=acceptedDetails(current.details,name,values,tees);const saved=await api.saveCourse(current,name,details);current=saved;courses=courses.map(c=>c.id===saved.id?saved:c);render(saved);$('courseSelect').selectedOptions[0].textContent=saved.name;feedback('Accepted course details saved. Return to customer review to check and tick this course.');message(`${saved.name}: accepted details saved successfully.`);$('saveFeedback').scrollIntoView({block:'center'});});};
 client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){$('catalogue').hidden=true;$('courseEditor').hidden=true;current=null;dirty=false;message('Signed out. Sign in with your owner email to edit courses.');}});
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
}
initialise().catch(e=>message(e.message,true));
