import {createGroupApi,validateAccountConfig} from './group-api.mjs';
import {states,streetTypes,playerDetails,matches,saveArguments} from './roster-model.mjs';
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let client,api,groups=[],selected='',players=[],editing=null,pendingInactive=null,busy=false,generation=0;
function message(text,error=false){$('rosterMessage').textContent=text;$('rosterMessage').classList.toggle('error',error);}
function hideEditor(){editing=null;pendingInactive=null;$('onlineEditor').hidden=true;$('onlineEditor').replaceChildren();$('inactiveConfirmation').hidden=true;}
function clear(){generation++;players=[];groups=[];selected='';hideEditor();['activeRoster','inactiveRoster','rosterGroup'].forEach(id=>$(id).replaceChildren());['rosterAccount','onlineRoster'].forEach(id=>$(id).hidden=true);}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.message||'Unable to connect. Your form has been kept open. Please try again.',true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function button(parent,label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>action(fn);parent.append(b);}
function render(){const g=groups.find(g=>g.id===selected);if(g)$('rosterAllowance').textContent=players.filter(p=>p.active).length+' / '+g.golfer_count+' approved active golfers';const search=$('rosterSearch').value;['activeRoster','inactiveRoster'].forEach(id=>$(id).replaceChildren());for(const active of [true,false]){const list=$(active?'activeRoster':'inactiveRoster'),rows=players.filter(p=>p.active===active&&matches(p,search));if(!rows.length){list.textContent=search?'No matching players.':'No players yet.';continue;}for(const p of rows){const row=document.createElement('div');row.className='roster-entry';const name=document.createElement('span');name.textContent=[p.name,p.details?.nickname?`(${p.details.nickname})`:'',p.details?.registration].filter(Boolean).join(' · ');const controls=document.createElement('div');button(controls,'Player Details',()=>edit(p));if(active)button(controls,'Move to Inactive Player List',()=>askInactive(p));else button(controls,'Reactivate',()=>setActive(p,true));row.append(name,controls);list.append(row);}}}
async function refresh(){const token=++generation;hideEditor();$('onlineRoster').hidden=true;players=[];render();const {data,error}=await client.auth.getUser();if(token!==generation)return;if(error||!data.user||data.user.is_anonymous){clear();message('Sign in through Groups & Organiser Accounts to access your online players.');return;}
 const next=await api.groups();if(token!==generation)return;groups=next.filter(g=>g.enabled&&g.setup_status==='active');$('rosterGroup').replaceChildren();groups.forEach(g=>{const o=document.createElement('option');o.value=g.id;o.textContent=g.name;$('rosterGroup').append(o);});$('rosterAccount').hidden=false;
 const desired=selected||new URL(location.href).searchParams.get('group')||sessionStorage.getItem('gesSelectedGroup');selected=groups.some(g=>g.id===desired)?desired:groups[0]?.id||'';
 if(!selected){message('There are no activated groups available. The owner must approve access and activate your setup first.');return;}$('rosterGroup').value=selected;await loadPlayers();}
async function loadPlayers(){const token=++generation,group=selected;hideEditor();players=[];render();$('onlineRoster').hidden=true;const rows=await api.players(group);if(token!==generation||selected!==group)return;players=rows;sessionStorage.setItem('gesSelectedGroup',group);document.querySelectorAll('.back-planning').forEach(link=>link.href='groups.html?group='+encodeURIComponent(group)+'#organiserHome');const g=groups.find(g=>g.id===group);$('rosterHeading').textContent=g.name+' · Group Players';$('onlineInstructions').textContent=(g.golfer_count?`You have indicated you have ${g.golfer_count} players in your golf group. `:'')+'Record the names and Golf Registration numbers (where applicable) of each golfer in your group here.';$('onlineRoster').hidden=false;const used=players.filter(p=>p.active).length;$('rosterAllowance').textContent=used+' / '+g.golfer_count+' approved active golfers';render();message('Players loaded from your group’s online records.');}
function field(label,id,value='',attributes=''){return `<label>${label}<input id="${id}" value="${esc(value)}" ${attributes}></label>`;}
function edit(row){pendingInactive=null;$('inactiveConfirmation').hidden=true;editing=structuredClone(row||{id:crypto.randomUUID(),revision:0,active:true,ga:null});const p=playerDetails(editing),a=p.addressDetails;const state=states.find(([c,n])=>[c.toLowerCase(),n.toLowerCase()].includes(String(a.state||'').toLowerCase()))?.[0]||a.state||'';
 $('onlineEditor').innerHTML=`<h2>Player Details</h2><p>First Name and Last Name are required. Save confirms that these details have been stored online.</p><form id="saveOnlinePlayer"><div class="gesNameFields">${field('First Name','onlineFirst',p.firstName,'required maxlength="80" autocomplete="given-name"')}${field('Last Name','onlineLast',p.lastName,'required maxlength="80" autocomplete="family-name"')}</div>${field('Nick Name','onlineNick',p.nickname,'maxlength="80"')}${field('Golf Registration No (where applicable)','onlineRegistration',p.registration,'maxlength="80" inputmode="numeric"')}${field('Cell Phone No','onlinePhone',p.cellPhone,'type="tel" maxlength="80" autocomplete="tel"')}<fieldset class="gesAddressFields"><legend>Address</legend><div class="gesHouseNumber">${field('House/Apt No','onlineHouse',a.houseNo,'maxlength="80"')}</div><div class="gesStreetRow">${field('Street Name','onlineStreet',a.streetName,'maxlength="160"')}<label>Street Type<select id="onlineType"><option value="">Choose</option>${streetTypes.map(t=>`<option ${a.streetType===t?'selected':''}>${t}</option>`).join('')}</select></label></div><label id="onlineOtherLabel" hidden>Other — please insert<input id="onlineOther" maxlength="80" value="${esc(a.otherStreetType)}"></label>${field('Suburb','onlineSuburb',a.suburb,'maxlength="160" autocomplete="address-level2"')}<div class="gesStateRow"><label>State<select id="onlineState"><option value="">Choose</option>${states.map(([c,n])=>`<option value="${c}" ${state===c?'selected':''}>${c} — ${n}</option>`).join('')}${state&&!states.some(([c])=>c===state)?`<option value="${esc(state)}" selected>${esc(state)} (saved)</option>`:''}</select></label>${field('Post Code','onlinePostCode',a.postCode,'maxlength="20" inputmode="numeric" autocomplete="postal-code"')}</div>${a.legacyAddress?`<label>Previously saved address<textarea id="onlineLegacy" maxlength="1000">${esc(a.legacyAddress)}</textarea></label>`:''}</fieldset><label>Notes<textarea id="onlineNotes" rows="4" maxlength="10000">${esc(p.notes)}</textarea></label><details><summary>Handicap & club details</summary>${field('Home club','onlineClub',p.homeClub,'maxlength="160"')}</details><div class="rowBtns"><button type="submit">Save Player</button><button type="button" class="secondary" id="cancelOnlineEdit">Cancel</button>${editing.revision?'<button type="button" class="secondary" id="editMoveInactive">Move to Inactive Player List</button>':''}</div></form>`;
 $('onlineOtherLabel').hidden=a.streetType!=='Other';$('onlineOther').required=a.streetType==='Other';$('onlineType').onchange=()=>{$('onlineOtherLabel').hidden=$('onlineType').value!=='Other';$('onlineOther').required=$('onlineType').value==='Other';};$('cancelOnlineEdit').onclick=hideEditor;if($('editMoveInactive'))$('editMoveInactive').onclick=()=>askInactive(editing);
 $('saveOnlinePlayer').onsubmit=e=>{e.preventDefault();action(async()=>{const val=id=>$(id).value.trim(),details={...p,firstName:val('onlineFirst'),lastName:val('onlineLast'),nickname:val('onlineNick'),registration:val('onlineRegistration'),cellPhone:val('onlinePhone'),notes:val('onlineNotes'),homeClub:val('onlineClub'),addressDetails:{houseNo:val('onlineHouse'),streetName:val('onlineStreet'),streetType:val('onlineType'),otherStreetType:val('onlineOther'),suburb:val('onlineSuburb'),state:val('onlineState'),postCode:val('onlinePostCode'),legacyAddress:$('onlineLegacy')?val('onlineLegacy'):''}};const token=generation,group=selected;const row=await api.savePlayerDetails(saveArguments(group,editing,details,editing.ga??null,editing.active));if(token!==generation||selected!==group)return;players=players.filter(p=>p.id!==row.id).concat(row);hideEditor();render();message(row.name+' saved online.');});};$('onlineEditor').hidden=false;$('onlineEditor').scrollIntoView({behavior:'smooth'});$('onlineFirst').focus();}
function askInactive(row){pendingInactive=structuredClone(row);$('inactiveQuestion').textContent=`Move ${row.name} to the Inactive Player List?`; $('inactiveConfirmation').hidden=false;$('inactiveConfirmation').scrollIntoView({behavior:'smooth'});}
async function setActive(row,active){if(active&&!row.active){const g=groups.find(g=>g.id===selected);if(players.filter(p=>p.active).length>=g.golfer_count)throw new Error('Approved active-player limit reached. Move a player to inactive first.');}if(!row.details?.firstName||!row.details?.lastName){edit(row);message('Please complete First Name and Last Name and save before changing the player’s status.');return;}const token=generation,group=selected;const result=await api.savePlayerDetails(saveArguments(group,row,row.details,row.ga,active));if(token!==generation||selected!==group)return;players=players.filter(p=>p.id!==result.id).concat(result);hideEditor();render();message(active?'Player reactivated.':'Player moved to the Inactive Player List. All details have been retained.');}
$('confirmInactive').onclick=()=>action(()=>setActive(pendingInactive,false));$('cancelInactive').onclick=()=>{pendingInactive=null;$('inactiveConfirmation').hidden=true;};$('newOnlinePlayer').onclick=()=>{const g=groups.find(g=>g.id===selected);if(players.filter(p=>p.active).length>=g.golfer_count){message('Your approved limit is '+g.golfer_count+' active golfers. Move a player to inactive or request an increased allowance.',true);return;}edit(null);};$('rosterSearch').oninput=render;$('reloadRoster').onclick=()=>action(()=>refresh());$('rosterGroup').onchange=()=>action(async()=>{selected=$('rosterGroup').value;await loadPlayers();});$('signOutRoster').onclick=()=>action(async()=>{clear();const {error}=await client.auth.signOut();if(error)throw error;sessionStorage.removeItem('gesSelectedGroup');message('Signed out.');});
try{const cfg=validateAccountConfig(window.GES_ACCOUNT_CONFIG);client=window.supabase.createClient(cfg.url,cfg.key,{auth:{storageKey:'golfEventScorerGroupAuth',persistSession:true,detectSessionInUrl:false,autoRefreshToken:true}});api=createGroupApi(client);client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){clear();message('Signed out. Sign in through Groups & Organiser Accounts.');}});await action(refresh);}catch(e){clear();message(e.message,true);}
